services:
  web:
    build: ./app-kpi
    restart: always
    ports:
      - "80:80"
    networks:
      - app-network
  api:
    build: ./kpi-api
    restart: always
    environment:
      DB_HOST: 192.168.109.118
      DB_USER: pn
      DB_PASS: 4321
      DB_DATABASE: spbkpi
      PORT: 5000
    ports:
      - "5000:5000"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge